# -*- coding: utf-8 -*-
"""Blood caffeine levels py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pr9KZXzbZYmhEudqQ0uR5Z_MmQAp9Prm
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
import re
from datetime import datetime
import pytz

#graph params
hrs_amnt = 32
y_const = 40

tz_Tln = pytz.timezone('Europe/Tallinn') 
now = datetime.now(tz_Tln)
current_time = now.strftime("%H.%M")

#sessional variables
if "intake" not in st.session_state:
    st.session_state.intake = []
if "table_list" not in st.session_state:
    st.session_state.table_list = []
if "drinks" not in st.session_state:
    st.session_state.drinks = []
if "custom_state" not in st.session_state:
    st.session_state.custom_state = False
if "custom_drink" not in st.session_state:
    st.session_state.custom_drink = ""
if "custom_caff" not in st.session_state:
    st.session_state.custom_caff = ""
if "curr_caff_lvl" not in st.session_state:
    st.session_state.curr_caff_lvl = 0
if "safe_to_sleep" not in st.session_state:
    st.session_state.safe_to_sleep = True
if "b_mass" not in st.session_state:
    st.session_state.b_mass = ""
if "m_speed" not in st.session_state:
    st.session_state.m_speed = ""

enable_custom = st.session_state.custom_state

#drinks preset
caffeine_amount = {
    "Espresso": 65,
    "Double espresso": 130,
    "Filter coffee": 110,
    "Latte": 65,
    "Cappuccino": 65,
    "Flat white": 130,
    "Black tea (300ml)": 60,
    "Green tea (300ml)": 40,
    "Energy drink (250ml)": 75,
    "Energy drink (500ml)": 150
}

metabolism_speed_values = {
    "Fast": 3.5,
    "Regular": 5.7,
    "Slow": 7
}

#helper functions
def check_time_format(time):
    if len(time) > 0 and "." in time:
        time_list = time.split(".")
        time_1 = time_list[0]
        time_2 = time_list[1]
        if 1 <= len(time_1) <= 2 and 1 <= len(time_2) <= 2:
            if int(time_1) < 24 and int(time_2) < 60:
                return True
    else:
        return False

def ticks(amount):
  tick = []
  for i in range(amount):
    x = i
    tick.append(x)
  return tick

def strings(ticks):
  strings = []
  for i in range(len(ticks)):
    strings.append(f"{ticks[i % 24]}:00")
  return strings

def time_to_int(time):
    time_list = time.split(".")
    time_1 = int(time_list[0])
    time_2 = int(time_list[1])
    time_int = round((time_1 + (time_2 / 60)), 2)
    return time_int

#input handling
def handle_input(drink, time, cust_caff_amnt):
    print("start check")
    try:
        if time == "":
            st.info('No time...', icon="🕙")
            return None
        elif not check_time_format(time):
            st.info('Check time format (ex: 12.30)', icon="🕙")
            return None
        elif drink in caffeine_amount:
            est_caffeine = caffeine_amount[drink]
            return time, drink, est_caffeine

        elif cust_caff_amnt == "" and drink:
            st.info('No caffeine amount, yet there is a drink...', icon="🤔")
            return None
        elif cust_caff_amnt and drink == "":
            st.info('No custom drink, yet there is a caffeine amount...', icon="🤔")
            return None
        elif cust_caff_amnt == "" and drink == "":
            st.info('Did you want to add a preset drink?', icon="🤔")
            return None
        elif not re.match(r"^\d+$", cust_caff_amnt):
            st.info("Only numbers are allowed.")
            return None
        elif int(cust_caff_amnt) <= 1 or int(cust_caff_amnt) >= 1000:
            st.info("Invalid number.")
            return None

        elif drink not in caffeine_amount:
            est_caffeine = int(cust_caff_amnt)
            return time, drink, est_caffeine
        else:
            st.info('Uhh, what?')
            return None
    except Exception as e:
        return None

#data handling
def add_data(time, drink, est_caffeine, body_mass, metabol_speed):
    st.session_state.drinks.append(drink)
    intake_tuple = (time, est_caffeine)
    st.session_state.intake.append(intake_tuple)
    st.session_state.table_list = []
    st.session_state.b_mass = body_mass
    st.session_state.m_speed = metabol_speed
    for i in range(len(st.session_state.intake)):
        temp_dict = {"Time": st.session_state.intake[i][0], "Drink":  st.session_state.drinks[i], "Estimated caffeine, mg": st.session_state.intake[i][1]}
        st.session_state.table_list.append(temp_dict)
    return

#main script logic
def absorption_half_life(intake, start_time, hours, start_caff, body_mass, half_life):
    try:
        x = np.linspace(start_time, hours, 300)
        
        intake_len = len(intake)
        
        curr_caff = start_caff
        
        decay_start = 0
        
        y = np.zeros_like(x)

        for i in range(intake_len):
    
            #absorption
            intake_time = time_to_int(intake[i][0])
            intake_caff = intake[i][1]

            curr_conc = curr_caff / body_mass
            start_x = intake_time
            start_y = curr_conc
            
            curr_caff = curr_caff + intake_caff
            curr_conc = curr_caff / body_mass

            decay_start = intake_time + 0.75
            end_x = decay_start
            end_y = curr_conc
        
            # Calculate absorption only for the absorption phase
            y_absorption_full = start_y + ((end_y - start_y) / (end_x - start_x)) * (x - start_x)
            y_absorption = np.where((x >= start_x) & (x <= end_x), y_absorption_full, 0)
        
            #decay
            # Calculate decay starting from decay_start
            y_decay_full = curr_caff * (0.5)**((x - decay_start)/half_life)
        
            if i != (intake_len - 1):
              x_stop = time_to_int(intake[i+1][0])
              y_decay = np.where((x > end_x) & (x <= x_stop), y_decay_full, 0)
              # Update curr_caff for the next absorption phase based on decay at x_stop
              if np.any(x >= x_stop):
                  curr_caff = curr_caff * (0.5)**((x_stop - decay_start)/half_life)
            else:
                y_decay = np.where(x > end_x, y_decay_full, 0)
    
            y += y_absorption + y_decay
    except Exception as e:
        print(f"An error occurred: {e}")
    return x, y

#get caff for current time
def current_caffeine_level(x, y):
    line, = plt.plot(x, y)
    x_data = line.get_xdata()
    y_data = line.get_ydata()

    target_x = time_to_int(current_time)
    y_value = np.interp(target_x, x_data, y_data)
    return round(y_value)

#calculate is it safe to sleep
def safe_to_sleep(current_caffeine_level):
    if current_caffeine_level < 40:
        return True
    else:
        return False

def actions_on_show():
    body_mass_int = int(st.session_state.body_m)
    metabolism_s = metabolism_speed_values[st.session_state.m_speed]
    
    x_plot, y_plot = absorption_half_life(st.session_state.intake, 0, 30, 0, body_mass_int, metabolism_s)

    st.session_state.curr_caff_lvl = current_caffeine_level(x_plot, y_plot)
    curr_caff_level = st.session_state.curr_caff_lvl
    st.session_state.safe_to_sleep = safe_to_sleep(curr_caff_level)
    safe_to_sleep_value =  st.session_state.safe_to_sleep
    
    plt.clf()
    plt.plot(x_plot, y_plot)
    plt.xticks(ticks(hrs_amnt), strings(ticks(hrs_amnt)), rotation=45)
    plt.xlabel('time')
    plt.ylabel('caffeine, mg')
    plt.axhline(y=y_const, color='r', linestyle='--')
    plt.legend()
    plt.tight_layout()
    st.pyplot(plt.gcf())
    return

#containers
input_container = st.container()
data_table_container = st.container()
graph_container = st.container()
graph_data_container = st.container()

col1, col2 = st.columns(2)

with col1:
    with input_container:
        col1_1, col1_2 = st.columns(2)
        with col1_1:   
            time = st.text_input("Time", placeholder="00.00")
            drink = st.selectbox(
            "Drink",
            ("Espresso", 
            "Double espresso", 
            "Filter coffee", 
            "Latte", 
            "Cappuccino", 
            "Flat white", 
            "Black tea (300ml)", 
            "Green tea (300ml)", 
            "Energy drink (250ml)", 
            "Energy drink (500ml)"),
            disabled = enable_custom
            )

        with col1_2:
            body_mass = st.text_input("Approximate body mass, kg", 
                placeholder="70kg"
            )
            metabol_speed = st.selectbox("Approximate metabolism speed",
                ("Slow",
                "Average",
                "Fast")
            )
            enable_custom = st.checkbox(
                "Add custom drink.", 
                value = st.session_state.get("custom_state", False), 
                key = "custom_state"
            )
            custom_drink = st.text_input("Custom drink", 
                value = "",
                key = "custom_drink",
                placeholder = "Drink",
                disabled = not enable_custom
            )
            custom_caff = st.text_input("Caffeine amount, mg", 
                value = "",
                key = "custom_caff",
                placeholder="100", 
                disabled = not enable_custom
            )

with col2:
    with data_table_container:   
        if st.button("Add"):
            if not enable_custom:
                result = handle_input(drink, time, None)
                result.append(body_mass)
                result.append(metabol_s)
            else: 
                result = handle_input(custom_drink, time, custom_caff)
                result.append(body_mass)
                result.append(metabol_s)
            if result:
                add_data(*result) 

        if st.button("Clear"):
            st.session_state.intake = []
            st.session_state.table_list = []
            st.session_state.drinks = []
            st.session_state.curr_caff_lvl = 0
            st.session_state.safe_to_sleep = True

        st.table(data=st.session_state.table_list)

with graph_container:
    if st.button("Show"):
        actions_on_show()

with graph_data_container:
    curr_caff_level = st.session_state.curr_caff_lvl
    safe_to_sleep_value = st.session_state.safe_to_sleep
    st.text(f"Current caffeine level at {current_time} EET: {curr_caff_level}mg.")

