# -*- coding: utf-8 -*-
"""Blood caffeine levels py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pr9KZXzbZYmhEudqQ0uR5Z_MmQAp9Prm
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
import re


if "intake" not in st.session_state:
    st.session_state.intake = []
if "table_list" not in st.session_state:
    st.session_state.table_list = []
if "drinks" not in st.session_state:
    st.session_state.drinks = []
    
time = st.text_input("Time", placeholder="00.00")

custom_drink = st.text_input("Custom drink", placeholder="Drink")
custom_caff = st.text_input("Caffeine amount, mg", placeholder="100")

drink = st.selectbox(
    "Drink",
    ("Espresso", 
    "Double espresso", 
    "Filter coffee", 
    "Latte", 
    "Cappuccino", 
    "Flat white", 
    "Black tea (300ml)", 
    "Green tea (300ml)", 
    "Energy drink (250ml)", 
    "Energy drink (500ml)")
)

caffeine_amount = {
    "Espresso": 65,
    "Double espresso": 130,
    "Filter coffee": 110,
    "Latte": 65,
    "Cappuccino": 65,
    "Flat white": 130,
    "Black tea (300ml)": 60,
    "Green tea (300ml)": 40,
    "Energy drink (250ml)": 75,
    "Energy drink (500ml)": 150
}

def check_time_format(time):
    if len(time) > 0 and "." in time:
        time_list = time.split(".")
        time_1 = time_list[0]
        time_2 = time_list[1]
        if 1 <= len(time_1) <= 2 and 1 <= len(time_2) <= 2:
            if int(time_1) < 24 and int(time_2) < 60:
                return True
    else:
        return False

def handle_input(drink, time, cust_caff_amnt):
    print("start check")
    try:
        if drink in caffeine_amount:
            if (drink or cust_caff_amnt) and time == "":
                st.info('No time...', icon="🕙")
                return None
            elif not check_time_format(time):
                st.info('Check time format (ex: 12.30)', icon="🕙")
                return None
            else:
                drink and check_time_format(time)
                est_caffeine = caffeine_amount[drink]
                return time, drink, est_caffeine
        elif drink not in caffeine_amount:
            if cust_caff_amnt == "" and drink:
                st.info('No caffeine amount, yet there is a drink...', icon="🤔")
                return None
            if cust_caff_amnt and drink == "":
                st.info('No custom drink, yet there is a caffeine amount...', icon="🤔")
                return None
            elif not re.findall(r"^\dt$", cust_caff_amnt):
                st.info("Only numbers are allowed.")
                return None
            elif int(cust_caff_amnt) <= 1 or int(cust_caff_amnt) >= 1000:
                st.info("Invalid number.")
                return None
            else:
                drink and check_time_format(time):
                est_caffeine = int(cust_caff_amnt)
                return time, drink, est_caffeine
        else:
            st.info('Uhh, what?')
            return None
    except Exception as e:
        return None

def add_data(time, drink, est_caffeine):
    st.session_state.drinks.append(drink)
    intake_tuple = (time, est_caffeine)
    st.session_state.intake.append(intake_tuple)
    st.session_state.table_list = []
    for i in range(len(st.session_state.intake)):
        temp_dict = {"Time": st.session_state.intake[i][0], "Drink":  st.session_state.drinks[i], "Estimated caffeine, mg": st.session_state.intake[i][1]}
        st.session_state.table_list.append(temp_dict)
    return

if st.button("Add"):
    if custom_drink == "" and custom_caff == "":
        time, drink, est_caffeine = handle_input(drink, time, None)
        add_data(time, drink, est_caffeine)
    else: 
        time, drink, est_caffeine = handle_input(custom_drink, time, custom_caff)
        add_data(time, drink, est_caffeine)

    
if st.button("Clear"):
    st.session_state.intake = []
    st.session_state.table_list = []
    st.session_state.drinks = []
                 
st.table(data=st.session_state.table_list)

def time_to_int(time):
    time_list = time.split(".")
    time_1 = int(time_list[0])
    time_2 = int(time_list[1])
    time_int = round(time_1 + (time_2 / 60))
    return time_int

def absorption_half_life(intake, start_time, hours, start_caff):
    try:
        x = np.linspace(start_time, hours, 60)
        half_life = 5.70
        
        intake_len = len(intake)
        
        curr_caff = start_caff
        
        decay_start = 0
        
        y = np.zeros_like(x)

        for i in range(intake_len):
    
            #absorption
            intake_time = time_to_int(intake[i][0])
            intake_caff = intake[i][1]
        
            start_x = intake_time
            start_y = curr_caff
            curr_caff = curr_caff + intake_caff
            decay_start = intake_time + 0.75
            end_x = decay_start
            end_y = curr_caff
        
            # Calculate absorption only for the absorption phase
            y_absorption_full = start_y + ((end_y - start_y) / (end_x - start_x)) * (x - start_x)
            y_absorption = np.where((x >= start_x) & (x <= end_x), y_absorption_full, 0)
        
            #decay
            # Calculate decay starting from decay_start
            y_decay_full = curr_caff * (0.5)**((x - decay_start)/half_life)
        
            if i != (intake_len - 1):
              x_stop = time_to_int(intake[i+1][0])
              y_decay = np.where((x > end_x) & (x <= x_stop), y_decay_full, 0)
              # Update curr_caff for the next absorption phase based on decay at x_stop
              if np.any(x >= x_stop):
                  curr_caff = curr_caff * (0.5)**((x_stop - decay_start)/half_life)
            else:
                y_decay = np.where(x > end_x, y_decay_full, 0)
    
            y += y_absorption + y_decay
    except Exception as e:
        print(f"An error occurred: {e}")
    return x, y

hrs_amnt = 32
y_const = 40

def ticks(amount):
  tick = []
  for i in range(amount):
    x = i
    tick.append(x)
  return tick

def strings(ticks):
  strings = []
  for i in range(len(ticks)):
    strings.append(f"{ticks[i % 24]}:00")
  return strings

if st.button("Show"):
    x_plot, y_plot = absorption_half_life(st.session_state.intake, 0, 30, 0)
    plt.plot(x_plot, y_plot)
    plt.xticks(ticks(hrs_amnt), strings(ticks(hrs_amnt)), rotation=45)
    plt.xlabel('time')
    plt.ylabel('caffeine, mg')
    plt.axhline(y=y_const, color='r', linestyle='--')
    plt.legend()
    plt.tight_layout()
    st.pyplot(plt.gcf())
    



